---
- hosts: 192.168.56.106
  become: true
  tasks:

  - name: install apache2 and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package}}"
      state: latest
      update_cache: yes
